medkom/medkom/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'message.views.home', name='home'),
    url(r'^messages/', include('message.urls')),
    url(r'^wilayah/', include('wilayah.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^member/', include('member.urls')),
    
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

medkom/message/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'message.views.messages', name='messages'),
    
    url(r'^(?P<msg_id>\d+)/$', 'message.views.view_message'),
    url(r'^(?P<msg_id>\d+)/decline/$', 'message.views.decline'),
    url(r'^(?P<msg_id>\d+)/delete/$', 'message.views.delete'),
    url(r'^(?P<msg_id>\d+)/reply/$', 'message.views.reply'),
    
    url(r'^new/$', 'message.views.new_message', name="new_message"),
    url(r'^new/(?P<no_hp>\d+)/$', 'message.views.new_single_message'),
    
    url(r'^archive/$', 'message.views.archive', name='archive'),
    url(r'^log/$', 'message.views.log', name='log'),
    
    url(r'^settings/broadcast/$', 'message.views.broadcast', name='broadcast'),
    url(r'^settings/broadcast/(?P<b_id>\d+)/$', 'message.views.view_broadcast'),
    url(r'^settings/broadcast/(?P<b_id>\d+)/delete/$',
        'message.views.delete_broadcast'),
)

medkom/message/models.py
from django.db import models
from member.models import Person

class Queue(models.Model):
    date = models.DateTimeField()
    sender = models.CharField(max_length=20)
    message = models.CharField(max_length=200)
    MSG_STATUS = (
        (0, 'Moderated'),
        (1, 'Pending'),
    )
    status = models.IntegerField(choices=MSG_STATUS, default=0)
    
    MSG_RESOLUTION = (
        (0, 'Approved'),
        (1, 'Decline'),
    )
    resolution = models.IntegerField(choices=MSG_RESOLUTION, null=True)
    
    def __unicode__(self):
        return u'%s' %(self.id)

class Broadcast(models.Model):
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=15)

    def __unicode__(self):
        return u'%s : %s' %(self.name,self.phone)

class Log(models.Model):
    date = models.DateTimeField()
    message = models.CharField(max_length=200)
    persons = models.ManyToManyField(Person)
    queue = models.ForeignKey(Queue, null=True, blank=True)
    
    def __unicode__(self):
        return u'%s' % self.message
    
    

medkom/message/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from accounts.decorators import admin_required
from django.db.models import Q, F
from django.db import connection, transaction
from message.models import Queue, Log, Broadcast
from message.forms import (DeleteMessagesForm, BroadcastForm,
                           SettingBroadcastForm, ReplyForm, SearchForm)
from member.models import Person, Usia, StatusSosial
import datetime

@login_required
def home(request):
    if request.method == "POST":
        form = DeleteMessagesForm(request.POST)
        if form.is_valid():
            if not form.cleaned_data["queue"] == '':
                list_messages = [x for x in form.cleaned_data["queue"].split(',')]
                messages = Queue.objects.filter(id__in=list_messages)
                messages.delete()
            
            return HttpResponseRedirect(reverse('home'))
    else:
        form = DeleteMessagesForm()
    
    queue_list = Queue.objects.filter(status__exact="1").order_by('-id')
    paginator = Paginator(queue_list, 5)
    page = request.GET.get('page')
    try:
        messages = paginator.page(page)
    except PageNotAnInteger:
        messages = paginator.page(1)
    except EmptyPage:
        messages = paginator.page(paginator.num_pages)
    
    return render_to_response('message/home.html',
                              {"messages": messages, "form": form, },
                              context_instance=RequestContext(request))

@login_required
def messages(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        queue_list = ''
        if form.is_valid():
            q = form.cleaned_data["q"]
            persons = Person.objects.exclude(no_handphone='').filter(nama_lengkap__icontains=q)
            queryset = Q()
            for person in persons:
                queryset.add(Q(
                    sender__icontains=person.no_handphone[1:]
                ), Q.OR)
            
            queryset.add(Q(
                message__icontains=q
            ), Q.OR)
            
            queue_list = Queue.objects.filter(queryset)
    else:
        form = SearchForm()
        queue_list = Queue.objects.all().order_by('-id')
        
    paginator = Paginator(queue_list, 5)
    page = request.GET.get('page')
    try:
        messages = paginator.page(page)
    except PageNotAnInteger:
        messages = paginator.page(1)
    except EmptyPage:
        messages = paginator.page(paginator.num_pages)
        
    return render_to_response("message/messages.html",
                              {"messages": messages, "form":form, },
                              context_instance=RequestContext(request))

@login_required
def view_message(request, msg_id):
    queue = get_object_or_404(Queue, pk=msg_id)
    if request.method == 'POST':
        form = BroadcastForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message"]
            # Send to member
            if form.cleaned_data["member"]:
                queryset = _get_queryset(form)
                if queryset:
                    persons = Person.objects.filter(queryset)
                else:
                    persons = Person.objects.all()
                    
                _send_sms(persons, message)
                _write_log(persons, message, queue)
                
                # Modify message
                queue.status = 0 #processed
                queue.resolution = 0 #approved
                queue.save()
            
            if form.cleaned_data["external"]:
                if form.cleaned_data["extra_phones"]:
                    phones = form.cleaned_data["extra_phones"].split(',')
                    for phone in phones:
                        _send_single_sms(phone, message)
                        
            return HttpResponseRedirect(reverse('home'))
    else:
        form = BroadcastForm(initial={
            'message': queue.message
        })
    
    return render_to_response("message/view_message.html",
                              {"message": queue, "form": form, },
                              context_instance=RequestContext(request))

@login_required
def new_message(request):
    if request.method == 'POST':
        form = BroadcastForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message"]
            
            #Send Member
            if form.cleaned_data["member"]:
                queryset = _get_queryset(form)
                if queryset:
                    persons = Person.objects.filter(queryset)
                else:
                    persons = Person.objects.all()
                    
                _send_sms(persons, message)
                _write_log(persons, message)
            
            #Send External Receiver
            if form.cleaned_data["external"]:
                if form.cleaned_data["extra_phones"]:
                    phones = form.cleaned_data["extra_phones"].split(',')
                    for phone in phones:
                        _send_single_sms(phone, message)
            
            return HttpResponseRedirect(reverse('home'))
    else:
        form = BroadcastForm()
    
    return render_to_response("message/new_message.html",
                              {"form": form,},
                              context_instance=RequestContext(request))

@login_required
def decline(request, msg_id):
    if request.method == 'POST':
        queue = get_object_or_404(Queue, pk=request.POST.get('msg-id'))
        queue.status = 0
        queue.resolution = 1
        queue.save()
    
    return HttpResponseRedirect(reverse('home'))

@login_required
def delete(request, msg_id):
    if request.method =='POST':
        message = get_object_or_404(Queue, pk=request.POST.get('del-id'))
        message.delete()
    
    return HttpResponseRedirect(reverse('home'))

@admin_required
def broadcast(request):
    if request.method == "POST":
        form = SettingBroadcastForm(request.POST)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect(reverse('broadcast'))
    else:
        form = SettingBroadcastForm()
        
    broadcasts = Broadcast.objects.all()
    
    return render_to_response("message/broadcast.html",
                              {"broadcasts": broadcasts, "form":form,},
                              context_instance=RequestContext(request))

@admin_required
def view_broadcast(request, b_id):
    broadcast = get_object_or_404(Broadcast, pk=b_id)
    if request.method == "POST":
        form = SettingBroadcastForm(request.POST, instance=broadcast)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect(reverse('broadcast'))
    else:
        form = SettingBroadcastForm(instance=broadcast)
        
    return render_to_response("message/view_broadcast.html",
                              {"broadcast":broadcast, "form":form,},
                              context_instance=RequestContext(request))

@admin_required
def delete_broadcast(request, b_id):
    if request.method == "POST":
        broadcast = get_object_or_404(Broadcast, pk=request.POST.get('b-id'))
        broadcast.delete()
        
    return HttpResponseRedirect(reverse('broadcast'))

@login_required
def archive(request):
    log_list = Log.objects.all().order_by('-id')
    paginator = Paginator(log_list, 10)
    page = request.GET.get('page')
    
    try:
        archives = paginator.page(page)
    except PageNotAnInteger:
        archives = paginator.page(1)
    except EmptyPage:
        archives = paginator.page(paginator.num_pages)
        
    return render_to_response(
        "message/archive.html",
        {"archives": archives, },
        context_instance=RequestContext(request)
    )

@login_required
def log(request):
    items = _fetch_sentitems()
    paginator = Paginator(items, 10)
    page = request.GET.get('page')
    try:
        sentitems = paginator.page(page)
    except PageNotAnInteger:
        sentitems = paginator.page(1)
    except EmptyPage:
        sentitems = paginator.page(paginator.num_pages)
    
    return render_to_response(
        "message/log.html",
        {"sentitems":sentitems,},
        context_instance=RequestContext(request)
    )

@login_required
def reply(request, msg_id):
    msg = get_object_or_404(Queue, pk=msg_id)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message"]
            destination = form.cleaned_data["destination"]
            _send_single_sms(destination, message)
            _write_single_log(message)
            
            # Modify message
            msg.status = 0 #processed
            msg.resolution = 0 #approved
            msg.save()
            
            return HttpResponseRedirect(reverse('home'))
    else:
        form = ReplyForm(
            initial={'destination': msg.sender}
        )
    
    return render_to_response("message/reply.html",
                              {"msg": msg, "form": form, },
                              context_instance=RequestContext(request))

@login_required
def new_single_message(request, no_hp):
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data["message"]
            destination = form.cleaned_data["destination"]
            _send_single_sms(destination, message)
            _write_single_log(message)
            
            return HttpResponseRedirect(reverse('home'))
    else:

medkom/message/templates/message/archive.html
{% extends "base.html" %}
{% block title %}Arsip Pengiriman Pesan{% endblock %}
{% block body %}
<div class="row">
    <div class="span5">
        <h4>Arsip Pengiriman Pesan</h4>
    </div>
    <div class="span5">
        <div class="pagination pull-right custom-pagination">
            <ul>
                <li class="disabled">
                    <a href="#">
                        Page {{ archives.number }} of
                        {{ archives.paginator.num_pages }}
                    </a>
                </li>
                {% if archives.has_previous %}
                    <li>
                        <a href="?page=1">
                            <i class="icon-fast-backward"></i>
                        </a>
                    </li>
                    <li>
                        <a href="?page={{ archives.previous_page_number }}">
                        <i class="icon-backward"></i>
                        </a>
                    </li>
                {% endif %}
                
                <li class="active"><a href="#">{{ archives.number }}</a></li>
                
                {% if archives.has_next %}
                    <li>
                        <a href="?page={{ archives.next_page_number }}">
                            <i class="icon-forward"></i>
                        </a>
                    </li>
                    <li>
                        <a href="?page={{ archives.paginator.num_pages }}">
                            <i class="icon-fast-forward"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div><!-- Paginator -->
    </div>
</div>
<p></p>
<div class="row">
    <div class="span10">
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>Pesan</th>
                </tr>
            </thead>
            <tbody>
                {% for archive in archives %}
                    <tr>
                        <td>
                            <div class="item-content">
                                {{ archive.message }}
                            </div>
                            <div class="item-footer">
                                <small>
                                    Date: {{ archive.date|date:"d-M-Y H:i:s" }} | 
                                    Ref: {{ archive.queue }} | 
                                    Sent Count: {{ archive.persons.count }}
                                </small>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

medkom/message/templates/message/broadcast.html
{% extends "base.html" %}
{% block title %}Pengaturan Pemberitahuan{% endblock %}
{% block body %}
    
    <div class="row">
        <div class="span5">
            <h4>Pengaturan Pemberitahuan</h4>
        </div>
        <div class="span5">
            <a data-toggle="tab" href="#new" class="btn btn-primary pull-right">
                Tambah
            </a>
        </div>
    </div>
    
    <div class="tab-content">
        <div class="tab-pane {% if not form.errors %}active{% endif %}" id="view">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>No HP</th>
                    </tr>
                </thead>
                <tbody id="table-list">
                    {% if broadcasts %}
                        {% for broadcast in broadcasts %}
                            <tr onclick="redirect('{{ broadcast.id }}')"
                                onmouseout="this.className='tr-mouse-out'"
                                onmouseover="this.className='tr-mouse-over'">
                                <td>{{ broadcast.name }}</td>
                                <td>{{ broadcast.phone }}</td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="4">
                                <p class="alert alert-info">
                                    Tidak ada data.
                                </p>
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane {% if form.errors %}active{% endif %}" id="new">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="#view" class="btn" data-toggle="tab">
                    Batal
                </a>
            </form>
        </div>
    </div>

    

    
{% endblock %}
{% block extrajs %}
    <script type="text/javascript">
        function redirect(page) {
            location.href=page;
        }
    </script>
{% endblock %}

medkom/message/templates/message/home.html
{% extends "base.html" %}
{% block title %}Selamat Datang{% endblock %}
{% block body %}
    
    <div class="row">
        <div class="span5" style="margin-top: 5px">
            <form method="post" style="margin: 0">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {{ form.queue.errors }}
                {{ form.queue }}
                
                <button type="submit" class="btn"
                    onclick="return confirmDelete()">
                    <i class="icon-remove-circle"></i>
                    Delete Selected
                </button>
            </form>
        </div>
        
        <div class="span5">
            <div class="pagination pull-right custom-pagination">
                <ul>
                    <li class="disabled">
                        <a href="#">
                            Page {{ messages.number }} of
                            {{ messages.paginator.num_pages }}
                        </a>
                    </li>
                    {% if messages.has_previous %}
                        <li>
                            <a href="?page=1">
                                <i class="icon-fast-backward"></i>
                            </a>
                        </li>
                        <li>
                            <a href="?page={{ messages.previous_page_number }}">
                            <i class="icon-backward"></i>
                            </a>
                        </li>
                    {% endif %}
                    
                    <li class="active"><a href="#">{{ messages.number }}</a></li>
                    
                    {% if messages.has_next %}
                        <li>
                            <a href="?page={{ messages.next_page_number }}">
                                <i class="icon-forward"></i>
                            </a>
                        </li>
                        <li>
                            <a href="?page={{ messages.paginator.num_pages }}">
                                <i class="icon-fast-forward"></i>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div><!-- Paginator -->
        </div>
    </div>
    <p></p>
    <table class="table table-hover" id="content">
        <thead>
            <tr>
                <th style="width: 10px">
                    <input type="checkbox" onclick="toggleChecked(this.checked)">
                </th>
                <th style="font-size: large">
                    Pesan
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="table-list">
            {% if messages %}
                {% load member_tags %}
                {% load tz %}
                
                {% for message in messages %}
                    <tr onmouseout="this.className='tr-mouse-out'"
                    onmouseover="this.className='tr-mouse-over'">
                        <td><input type="checkbox" value={{message.id}}></td>
                        <td  onclick="redirect('messages/{{ message.id }}')">
                            <div class="item-header">
                                <strong>
                                    {{message.sender}} {{message.sender|mask_sender}}
                                </strong>
                            </div>
                            <div class="item-content">
                                {{message.message}}
                            </div>
                            <div class="item-footer">
                                <small>
                                    {{message.date|date:"d-M-Y H:i:s"}}
                                </small>
                            </div>
                        </td>
                        <td onclick="redirect('messages/{{message.id}}/reply/')">
                            <i class="icon-share"></i>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4">
                        <p class="alert alert-info">
                            Tidak ada pesan.
                        </p>
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    
{% endblock %}

{% block extrajs %}
    <script type="text/javascript">
        function toggleChecked(status) {
            $('#table-list input').each(function() {
                $(this).attr("checked", status);
                $(this).trigger('change');
            })
        }
        
        function getSelectValues() {
            var allVals = [];
            $("#table-list :checked").each(function() {
                allVals.push($(this).val());
            });
            $("#id_queue").val(allVals);
        }
        
        $(function() {
            $("#table-list").change(getSelectValues);
            getSelectValues();
        });
        
        function confirmDelete() {
            var agree=confirm("Yakin akan menghapus data ini?");
            if(agree)
                return true;
            else
                return false;
        }
        
        function redirect(page) {
            location.href=page;
        }
        
        setInterval(function(){
            $('#content').load(location.href+" #content>*","");
        }, 300000);
    </script>
{% endblock %}

medkom/message/templates/message/log.html
{% extends "base.html" %}
{% block title %}Lihat log pesan{% endblock %}
{% block body %}

<div class="row">
    <div class="span5">
        <h4>Log pengiriman pesan</h4>
    </div>
    <div class="span5">
        <div class="pagination pull-right custom-pagination">
            <ul>
                <li class="disabled">
                    <a href="#">
                        Page {{ sentitems.number }} of
                        {{ sentitems.paginator.num_pages }}
                    </a>
                </li>
                {% if sentitems.has_previous %}
                    <li>
                        <a href="?page=1">
                            <i class="icon-fast-backward"></i>
                        </a>
                    </li>
                    <li>
                        <a href="?page={{ sentitems.previous_page_number }}">
                        <i class="icon-backward"></i>
                        </a>
                    </li>
                {% endif %}
                
                <li class="active"><a href="#">{{ sentitems.number }}</a></li>
                
                {% if sentitems.has_next %}
                    <li>
                        <a href="?page={{ sentitems.next_page_number }}">
                            <i class="icon-forward"></i>
                        </a>
                    </li>
                    <li>
                        <a href="?page={{ sentitems.paginator.num_pages }}">
                            <i class="icon-fast-forward"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div><!-- Paginator -->
    </div>
</div>
<p></p>
<div class="row">
    <div class="span10">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Pesan</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for item in sentitems %}
                    <tr>
                        <td>
                            <div class="item-header">
                                <strong>{{ item.DestinationNumber }}</strong>
                            </div>
                            <div class="item-content">
                                {{ item.TextDecoded }}
                            </div>
                            <div class="item-footer">
                                <small>{{ item.SendingDateTime }}</small>
                            </div>
                        </td>
                        <td>{{ item.Status }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

medkom/message/templates/message/new_single_message.html
{% extends "base.html" %}
{% block title %}Kirim SMS{% endblock %}
{% block body %}
    {% load member_tags %}
    <h4>Kirim SMS</h4>
    <p>Tujuan : {{ destination }}</p>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="btn btn-primary">Kirim</button>
        <a href="{% url home %}" class="btn btn-inverse">Batal</a>
    </form>
{% endblock %}
{% block extrajs %}
    <style>
        #id_message {
            width: 400px;
        }
        
        select {
            width: 210px;
        }
    </style>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('#id_message').limitCharacters();
        });
        $('.errorlist').attr('class', 'alert alert-error');
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/box.js"></script>
{% endblock %}

medkom/message/templates/message/reply.html
{% extends "base.html" %}
{% block title %}Balas SMS{% endblock %}
{% block body %}
    {% load member_tags %}
    <h4>Balas SMS</h4>
    <div class="well">
        <div class="item-header" style="font-size: large">
            <strong>{{ msg.sender }} {{msg.sender|mask_sender}}</strong>
        </div>
        <p></p>
        <div class="item-content" style="font-size: medium">
            <p>{{ msg.message }}</p>
        </div>
        <div class="item-footer">
            <small>{{msg.date|date:"d-M-Y"}}</small>
        </div>
    </div>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="btn btn-primary">Kirim</button>
        <a href="{% url home %}" class="btn btn-inverse">Batal</a>
    </form>
{% endblock %}
{% block extrajs %}
    <style>
        #id_message {
            width: 400px;
        }
        
        select {
            width: 210px;
        }
    </style>
    
    <script type="text/javascript">
        $(document).ready(function() {
            $('#id_message').limitCharacters();
        });
        $('.errorlist').attr('class', 'alert alert-error');
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/box.js"></script>
{% endblock %}

medkom/message/templates/message/view_broadcast.html
{% extends "base.html" %}
{% block title %}Lihat pengaturan pemberitahuan{{ broadcast.name }}{% endblock %}
{% block body %}
    
    <h4>{{ broadcast.name }}</h4>
    
    <div class="tab-content">
        <div class="tab-pane {% if not form.errors %}active{% endif %}" id="view">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <td>Nama</td>
                        <td>{{ broadcast.name }}</td>
                    </tr>
                    
                    <tr>
                        <td>No HP</td>
                        <td>{{ broadcast.phone }}</td>
                    </tr>
                </tbody>
            </table>
            
            <form method="post" action="delete/">
                {% csrf_token %}
                <input type="hidden" name="b-id" value="{{ broadcast.id }}">
                <a href="#new" class="btn btn-primary" data-toggle="tab">Edit</a>
                <button type="submit" class="btn btn-danger"
                onClick="return confirmDelete()">Hapus</button>
                <a href="../" class="btn btn-inverse">Kembali</a>
            </form>
            
        </div>
        
        <div class="tab-pane {% if form.errors %}active{% endif %}" id="new">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="#view" class="btn btn-inverse" data-toggle="tab">
                    Batal</a>
            </form>
        </div>
    </div>
    
{% endblock %}
{% block extrajs %}
    <script type="text/javascript">
        function confirmDelete() {
            var agree=confirm("Yakin akan menghapus data ini?");
            if(agree)
                return true;
            else
                return false;
        }
    </script>
{% endblock %}